sudo: false
language: javascript
install: true
branches:
  only:
  - master
before_script: make travis-init
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: git clone https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG;
    cd $TRAVIS_REPO_SLUG; make travis-deploy
  on:
    branch: master
- provider: npm
  skip_cleanup: true
  email: wangshijun2010@gmail.com
  api_key:
    secure: HsF8nPTI23oUvLCnBpqTm0qoYUcF+oDuRto4BF8cLHigQatSuM8XPq6JZEsPR5dZ4OM/RXHt2NPVi+nFgJSYkRsaRp22Eaouk4F/dzyoegdBX7jHwI8LEc/H8afxLr/aeF116pO1uwYy5STdymW8EbVWjeBHd9/incWDED/zkEsmX0tl1WSfx6l23t3eIeQ9ADF5PatX8PoLlwy5njAUm4n1MKbTK6T1BvbdSBCo7gLb8AS3GeuilIVHU9m4oBIK671TliO5rWpNP9p72es0lC4KILq/XiN1IEhO+GoLvzoy0UF4gDvidw0ZZMxYI0hyZAKbaZAzYWGjoxB8cDRtia1badXgcU+roJ1/bMrH/SYRlcjIe5+kwcXgtLNLlSvhsm4Vh1AQZPzm9qNMFOmkiZ5kkvkSATBzuwwYgBxmz9VyVOORBrfRkaDXJ0EeV4B6v8DsvbNjdHsQC2XLFxZTi0OLr9atYn3YJuykvEWvEHUotkH/tSi7Dbq+bEFtNIcXzm4p2xwNeIslaWDLWt20lpxQW9K2mCwESZ0X9goPaU05CMv6haB8zlwNKlDkAgoubWyHp7Rx/zDOHqCypq6iayma13CUdZSK5jll8KAcnySpoN21VPfZSSfkN/gTiCIg+ItbjYstiUDbqUbSIiNrIakNmCQQmYsYIye5HejpIlE=
  on:
    branch: master
env:
  global:
  - secure: uWahpVmtqR6ssj4aG8bl67QFkVYleuGCr2wlzmt8V6J8QK0GiTqXUbrmy4HLgjaStV/3+28Uj1GQjXRKyoagW/D+xKo2JAvIRyWub01/G9iTBWYe5lTfwyF3+0MiLQSK9nerGRrmUWotH+uvxh0Me0jev4mohFULpkTmRmv+YTm68m3TgVWmdC4veq7xUVbWIsClf+E9azl0o4UYP26ejrCAQhkSVUOjrtblRsWwd3VDZ6DCw6mr/R7gLkqxKo5P3EKsUBRmZ1p4lDTd6dkSSpv9qs17FE5jXzP0T2G7BYaSuZvDmFue993NZLvzmr9taV3a7dKkjvuXQfRfbSLo3T1eH1inzv8gOj5DehA0PqE3ZNQCizmEHMrZrxA9jpMrTS6G1dETuexMTmBkobqmYoakNxCrMQyu2NNI3l0HHJ2iVQJZUw33K/CDmNPW3YlbWL2EKMEBcUd2fEeETY99xNDfN88ASZ96wGSEazlCyX0fmlTCFRMQSfBhpiYxSR4WLqN2NY6Rntn75V6BqK7OcAha/Eu8j2RC63LbAlU9OA6FNsL2cl5qlI9nTm9wQ6cuPKyVSx9YYT9DlxHTE1FmU0QIaS0aYG7fflDLWvZItaVjx0R6bWkjU5jPRH8WfE8Qho04C2PFwdaAQLzLCp39hHeh/2OmNxaU6e2PuVlcO/0=
notifications:
  slack:
    secure: FIziWswVW6xViTLwT4ue2j5PJUBQh4yoR+R+3g/AmEiiulaPlDHnI6lg/oRoVLh/dWmvphoSSFpMD8OSiFKDxlz6gSngADX9tkl4cTdy1BVbq1VCJOSZpJyqICgDnAjB1PvcnPFXALCIWgdFoaQRmgtw92MPNDbRbWT2mBKzpOoE91AUkJQP4GncEgJGqWlSLw8KsrseCIRTtfb5VXgeW8iH0a2Khankpybn1vIdX9Rq/qarQ++Q9TJnjf+9ayJAwbljfnJ5OP8rftc/QClX3f5JTILi/7c2P3Wdhg3YgQRxGHNBuABtvdO6mm5aPmkLYnY+XayUfpOisoU/KifRI1SSioMmRyfsSuvu6I2aZydV1U20Dl6FSOahjGM59ebTJg2snaHRCBPtE08aczxVoFm0x+YN31Td68bo9CKRML2JDL2D4jtXO1tKzAjk89rTX3mXrsvGzoPtnfqqJ3Q764LGU2XlKQbhc1HDAMujM1ZZQHbAJJ/bt5ZwURlnCVHi8OSbCDim/rPYcjluI9N4GCRaCO9RjdSevHyRe0CQWR3TsPbDdMrWZYmghwq5+kx0bv5SFsKvvoCDwFZf4vFBZqjqTKyJUo25p1v9jhZ0gcITVo5ic0PiPf8+ajLOZ7GENz47f/jvQW9On2uqaK2QIO5FwGg3wK2r0YKTIPrUI8o=
