sudo: false
language: node_js
node_js:
  - '10'
install: true
cache:
  yarn: true
  directories:
    - 'node_modules'
branches:
  only:
    - master
before_script: make travis-init
script: make travis
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - git remote remove origin
      - git remote add origin "https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/ArcBlock/ocap-javascript-sdk.git"
      - make travis-deploy
    on:
      branch: master
env:
  global:
    - secure: 'qoUuXfloyohbFX7yusha83hgvRpN0Z4wgDzJ+3+aR7okI+Fpc0B+NTzFPkV3ihlPXgBbDSUztPBMrM5bOT/+c8JB4UmeGvqcwwGn4+eAETSiEIHpzk7NAE9vnN74Us1+pW5FCVuswgcxrnEe3i+UgKNL8rEUVmFR9fD3lr92Sxh2w+0K3M8ywXNuRleNEfDDM4jvVs48aKlz2jtpgbL+s6ZBskkqUXAJc+rCvaWqF3zFKfw8jwImCOM8yrEwXgpSt/jZQIK03Cs1U+vxxFiPsnmbVVWxEdgh+Wlf/nUnv+wEQmni8A2pz0Vpsi5AB/rAPm42eJAhXrR4udfTNNyj4eBulhmbwvgOjC7+UVn8WIu06FSGNHcbKViHPuoge2lRcdlPysw7068xlq+bHtMjegywqnCWOydgiGTTthZlAnV60JsmMLGJahpXYMCMO5GRi8Zhyjf7DeU0Xw/IQEMKxpXCgztzDDzjdpRJ9b44KvxobuB05XbLFgPbEPcfFg9AuQamZhBgOUAYzj1h3IUwdd5riKaDdY5nvO5qn9qjBXC9k8IB4xx+hl86IXDoux2aApshvNK/ldoo68J3/zyu9lAhgliA9YJolNqmYzoa1DLeF5mQ12tNEB6simtP3j70paVgAccrxqN6magaCuxgrS9C3P60r/RBZAbB3MwkoDU='
    - secure: 'pShgSfE+nMlwxcXQvhCSfyTi9zmqGTjFDfdGA4Jh7FFwdjnhT4xYqqNdRBSSor8bMy2LoJvujm3h+w4DTiuktQHhqFpATEo8uxI7Fdy8zItD5OPIaE/X0Da+ALFEUcl09PPqX9CPlzmhU91ErF8GeW+A3Voy4xaSwyp0W9S5YGTD8QIsngnMaFvJGS8mLLFJtxNap2d4MYcaGYYWbjZLPj4WqdBeJDtVMyeD2DoNLQh3FkGDvS/z+teSgPqBzZdeSjBKBzm2SOEuAKkJa7ZSqcvAQQO5ruKJfbj6BRBoVKyHj4pHPh3VFyEfmqjLO4D1N/TM/0SN6zJvHproHFbCKyIB+T1JbZvlK5j6z9FWQtxmJqb6KRyCPba1RD0pCn+sROisQquVNF62l+3R/6Dt5oPTbVWNAkveBB9Za01VzYB+bRD8h0gAiWArbWxSY4JqaZTVzE4mEwuD+wm9l55GSYHnhPZatOIelryCqcjdDzSN79uR/Upw25TM184Fwv7mBQkaKS0GrfrQPxMI0YsmFa5uy58qPq0CApcovP7lKH4mA/UTtdE0z0l+PPYo2n2GRPlqy9YO+zhkpeiLKSRjei35XF0pCMLaWNocRMc7yTqTrhbzlu2esQIbq9vBm5DRMyM1pezWaoRPoIwM00ylsTRP2GI9OYThJHOc7KwJfxY='
    - secure: "zPzopeSViEQd5VJnBzlH0wisRs99uVeGy4ksqR7g9rf5nNf50JXZluJUgeBDbw0SAfCTapARM+IpssibBhGQkv2tPLyax4huF1ejnvcfJ1WWgNgphwgyEK4SINfJ02gDvXsyF6BOysCwFnYrAdWw4rEY9ck0NGmIvheBfG3KUime7Xu0p/OnNbLYrERn4ZaI5o0osmarNLpqDh+8BTDLQgw4NTxuB8sgHCOhKAQQYlvx3eyiVz6PfhsvV//yxy+wnCxypqDyK8xeiO/bA63K/yQGq9Wf795JUTspPcr4j5Yo4LHle3r+J37p2jPwek0CV3aant2TIKEY72wgYnqFwOpx8A4h6NHkSHyzDjxEKtQtNyZGmWjuNZdh8OiVBkC9zsEAu5BpfNFdfEzFnouRc5teKrJFlGy+HhMSqQnfZUrv+fHNujV5PJO4cPxNf/4mQaG/tJaPfaz7MTzg3ujndb2oe5qAG2V2U67AQ2x5GVERW9t2b7bNR8WPnFqLv9Dc1o68X4SQYyfdH3/zXceJTsEBiPGTXhPmWhAeKDs9bNuX0Ucelfkv36kVuHhUCf0kGdfdhR/ZEQRT+nu2PNkK6Keyr/bre9hgDJiriM925imbloT9lEGD6WPJpgHw/G6utxg4v2izTCotX5ACDCumhyXLn6gHh5Xb4CCyDnIZuI4="
    - secure: "uVaz517+vIy1wnbjsEAE1jZxJVOWlnf2pBka66c0ngrnJd5TWAd3sSHPEIM1M8FhTzWVQz7HTP1mbb3ZZWhC7eBaKJXT0/QTGWpLJr06ZzHuDx8DjrEnonijR3AedgRagtXRJFjbTeLCDzZWkRrCCz5xrWaT3gFkyHF1dfiJT3P70iH3VruJblm6raGXuP1luHIMzA2CQ8z+Q2RGA6LTM7+BqG+KO2gDP9ArNYkiafOD+lCu0dHNdS/50G3tvpCF8Air8806askLeBLarntJpDabUSG6p2GvsQY0mBoxIY/lMWDZLWUTzDYx8AJoALmL0yC5x0hdlP7872WJBwrQqYn+us6ACJ6gveiYTw0ElC4+Xwmtrn0aYqe5/uc/sQlEjLnXjkjJIYT5V1UMYseSQjA+oG7e9cjhonbBaWyjAU45fCtPzkL2Xm+ePVXkDYHcv2rJQd2eFne0p3HRXjrIWkq5jMMou2OFNfBtEREVMrOYxvQ8d9bvC52m8bgGScmyCYJtg/JGYpDMuGR2QF2Fq+0Ejfe0hmL0uTgYedFTrjGQXDecguv1Kk3LTyM/Q17sR6WOihWxy9R5H4JEoorwMj1XS2miVv8dryKe2q4kCove+Bv6TfnLLt1C/XBH0kQGm3ciydF6O/moIGo4M6g2XED7cQ36MeU5y+ajZA9KYKI="
